# Generated by Django 4.0.3 on 2022-04-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_completed_alter_todo_order_alter_todo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='url',
            field=models.URLField(default=None, max_length=100, null=True),
        ),
    ]
